services:
  jpa:
    build: .
    container_name: jpaapp
    ports:
      - 8080:8080
  db:
    image: mysql:8.0.28
    container_name: mysql
    ports:
      - 3309:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: 'aziz'
      MYSQL_PASSWORD: 'aziz'
      MYSQL_DATABASE: 'gestion_employe'
      MYSQL_ROOT_PASSWORD: 'aziz'
    volumes:
      - ./backup/db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 1337:8080